apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: nginx-multitool
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 80
      name: nginx-port
    - protocol: TCP
      port: 9002
      targetPort: 8080
      name: multitool-port
